package(default_visibility = ["//visibility:public"])

java_library(
    name = "utilities",
    srcs = ["Utilities.java"],
    deps = [
        "//java/src/edu/berkeley/cs/graph",
        "//java/src/edu/berkeley/cs/graph:directedgraph",
    ],
)

java_test(
    name = "linkedlist",
    size = "small",
    srcs = ["LinkedList_T.java"],
    test_class = "edu.berkeley.cs.util.LinkedList_T",
    deps = [
        "//java/src/edu/berkeley/cs/util:linkedlist",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "splaylist",
    size = "small",
    srcs = ["SplayList_T.java"],
    test_class = "edu.berkeley.cs.util.SplayList_T",
    deps = [
        "//java/src/edu/berkeley/cs/util:splaylist",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "queue",
    size = "small",
    srcs = ["Queue_T.java"],
    test_class = "edu.berkeley.cs.util.Queue_T",
    deps = [
        "//java/src/edu/berkeley/cs/util:queue",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "stack",
    size = "small",
    srcs = ["Stack_T.java"],
    test_class = "edu.berkeley.cs.util.Stack_T",
    deps = [
        "//java/src/edu/berkeley/cs/util:stack",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "minheap",
    size = "small",
    srcs = ["MinHeap_T.java"],
    test_class = "edu.berkeley.cs.util.MinHeap_T",
    deps = [
        "//java/src/edu/berkeley/cs/util:minheap",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "treemap",
    size = "small",
    srcs = ["TreeMap_T.java"],
    test_class = "edu.berkeley.cs.util.TreeMap_T",
    deps = [
        "//java/src/edu/berkeley/cs/util:treemap",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "hashmap",
    size = "small",
    srcs = ["HashMap_T.java"],
    test_class = "edu.berkeley.cs.util.HashMap_T",
    deps = [
        "//java/src/edu/berkeley/cs/util:hashmap",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "hashset",
    size = "small",
    srcs = ["HashSet_T.java"],
    test_class = "edu.berkeley.cs.util.HashSet_T",
    deps = [
        "//java/src/edu/berkeley/cs/util:hashset",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "unionfind",
    size = "small",
    srcs = ["UnionFind_T.java"],
    test_class = "edu.berkeley.cs.util.UnionFind_T",
    deps = [
        "//java/src/edu/berkeley/cs/util:unionfind",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "radixtriemap",
    size = "small",
    srcs = ["RadixTrieMap_T.java"],
    test_class = "edu.berkeley.cs.util.RadixTrieMap_T",
    deps = [
        "//java/src/edu/berkeley/cs/util:hashset",
        "//java/src/edu/berkeley/cs/util:radixtriemap",
        "//thirdparty:junit4",
    ],
)
