test_suite(
    name = "program1",
    tests = [
        "//java/test/edu/berkeley/cs/app:warmup",
        "//java/test/edu/berkeley/cs/util:linkedlist",
        "//java/test/edu/berkeley/cs/util:splaylist",
    ],
)

test_suite(
    name = "program2",
    tests = [
        "//java/test/edu/berkeley/cs/app:calculator",
        "//java/test/edu/berkeley/cs/app:calculatorextracredit",
        "//java/test/edu/berkeley/cs/app/scheduling:fifoscheduler",
        "//java/test/edu/berkeley/cs/app/scheduling:job",
        "//java/test/edu/berkeley/cs/app/scheduling:roundrobinscheduler",
        "//java/test/edu/berkeley/cs/app/scheduling:shortestjobfirstscheduler",
        "//java/test/edu/berkeley/cs/util:minheap",
        "//java/test/edu/berkeley/cs/util:queue",
        "//java/test/edu/berkeley/cs/util:stack",
    ],
)

test_suite(
    name = "program3",
    tests = [
        "//java/test/edu/berkeley/cs/app:spellchecker",
        "//java/test/edu/berkeley/cs/app:summabletree",
        "//java/test/edu/berkeley/cs/util:hashmap",
        "//java/test/edu/berkeley/cs/util:hashset",
        "//java/test/edu/berkeley/cs/util:treemap",
    ],
)

test_suite(
    name = "program4",
    tests = [
        "//java/test/edu/berkeley/cs/sort:insertion",
        "//java/test/edu/berkeley/cs/sort:merge",
        "//java/test/edu/berkeley/cs/sort:quick",
        "//java/test/edu/berkeley/cs/sort:selection",
        "//java/test/edu/berkeley/cs/sort:shell",
    ],
)

test_suite(
    name = "program5",
    tests = [
        "//java/test/edu/berkeley/cs/graph",
        "//java/test/edu/berkeley/cs/graph:breadthfirstsearch",
        "//java/test/edu/berkeley/cs/graph:depthfirstorder",
        "//java/test/edu/berkeley/cs/graph:depthfirstsearch",
        "//java/test/edu/berkeley/cs/util:unionfind",
    ],
)

test_suite(
    name = "program6",
    tests = [
        "//java/test/edu/berkeley/cs/graph:cycle",
        "//java/test/edu/berkeley/cs/graph:directedgraph",
        "//java/test/edu/berkeley/cs/graph:stronglyconnectedcomponents",
        "//java/test/edu/berkeley/cs/graph:topologicalsort",
    ],
)

test_suite(
    name = "program7",
    tests = [
        "//java/test/edu/berkeley/cs/graph:minimumspanningtree",
        "//java/test/edu/berkeley/cs/graph:multiplesourceshortestpath",
        "//java/test/edu/berkeley/cs/graph:shortestpath",
    ],
)

test_suite(
    name = "program8",
    tests = [
        "//java/test/edu/berkeley/cs/app:plagiarismdetector",
        "//java/test/edu/berkeley/cs/util:radixtriemap",
    ],
)

test_suite(
    name = "final",
    tests = [
        "//java/test/edu/berkeley/cs/app/finalproject:duplicateusernames",
        "//java/test/edu/berkeley/cs/app/finalproject:fuzzysearch",
        "//java/test/edu/berkeley/cs/app/finalproject:hotkeygenerator",
        "//java/test/edu/berkeley/cs/app/finalproject:sortchecker",
    ],
)
