test_suite(
    name = "program1",
    tests = [
        "//java/test/edu/berkeley/cs/app:warmup",
    ],
)

test_suite(
    name = "program2",
    tests = [
        "//java/test/edu/berkeley/cs/app:calculator",
        "//java/test/edu/berkeley/cs/app:calculator_ec",
        "//java/test/edu/berkeley/cs/util:linkedlist",
        "//java/test/edu/berkeley/cs/util:queue",
        "//java/test/edu/berkeley/cs/util:splaylist",
        "//java/test/edu/berkeley/cs/util:stack",
    ],
)

test_suite(
    name = "program3",
    tests = [
        "//java/test/edu/berkeley/cs/sort:insertion",
        "//java/test/edu/berkeley/cs/sort:merge",
        "//java/test/edu/berkeley/cs/sort:quick",
        "//java/test/edu/berkeley/cs/sort:selection",
        "//java/test/edu/berkeley/cs/sort:shell",
    ],
)

test_suite(
    name = "program4",
    tests = [
        "//java/test/edu/berkeley/cs/app:summable_tree",
        "//java/test/edu/berkeley/cs/app/scheduling:fifo",
        "//java/test/edu/berkeley/cs/app/scheduling:job",
        "//java/test/edu/berkeley/cs/app/scheduling:rr",
        "//java/test/edu/berkeley/cs/app/scheduling:sjf",
        "//java/test/edu/berkeley/cs/util:minheap",
        "//java/test/edu/berkeley/cs/util:treemap",
    ],
)

test_suite(
    name = "program5",
    tests = [
        "//java/test/edu/berkeley/cs/app:spellchecker",
        "//java/test/edu/berkeley/cs/graph",
        "//java/test/edu/berkeley/cs/graph:bfs",
        "//java/test/edu/berkeley/cs/graph:dfs",
        "//java/test/edu/berkeley/cs/graph:dfsorder",
        "//java/test/edu/berkeley/cs/util:hashmap",
        "//java/test/edu/berkeley/cs/util:hashset",
    ],
)

test_suite(
    name = "program6",
    tests = [
        "//java/test/edu/berkeley/cs/graph:cycle",
        "//java/test/edu/berkeley/cs/graph:digraph",
        "//java/test/edu/berkeley/cs/graph:scc",
        "//java/test/edu/berkeley/cs/graph:toposort",
    ],
)

test_suite(
    name = "program7",
    tests = [
        "//java/test/edu/berkeley/cs/graph:mssp",
        "//java/test/edu/berkeley/cs/graph:mst",
        "//java/test/edu/berkeley/cs/graph:sp",
        "//java/test/edu/berkeley/cs/util:unionfind",
    ],
)

test_suite(
    name = "program8",
    tests = [
        "//java/test/edu/berkeley/cs/app:plagiarism",
        "//java/test/edu/berkeley/cs/util:trie",
    ],
)

test_suite(
    name = "final",
    tests = [
        "//java/test/edu/berkeley/cs/app/finalproject:duplicate_usernames",
        "//java/test/edu/berkeley/cs/app/finalproject:fuzzy_search",
        "//java/test/edu/berkeley/cs/app/finalproject:hotkey",
        "//java/test/edu/berkeley/cs/app/finalproject:sort_checker",
    ],
)
