package(default_visibility = ["//visibility:public"])

java_test(
    name = "calculator",
    size = "small",
    srcs = ["Calculator_T.java"],
    test_class = "edu.berkeley.cs.app.Calculator_T",
    deps = [
        "//java/src/edu/berkeley/cs/app",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "spellchecker",
    size = "small",
    srcs = ["SpellChecker_T.java"],
    test_class = "edu.berkeley.cs.app.SpellChecker_T",
    deps = [
        "//java/src/edu/berkeley/cs/app",
        "//java/src/edu/berkeley/cs/util",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "plagiarism",
    size = "small",
    srcs = ["PlagiarismDetector_T.java"],
    test_class = "edu.berkeley.cs.app.PlagiarismDetector_T",
    deps = [
        "//java/src/edu/berkeley/cs/app",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "fuzzy_search",
    size = "small",
    srcs = ["FuzzySearch_T.java"],
    test_class = "edu.berkeley.cs.app.FuzzySearch_T",
    deps = [
        "//java/src/edu/berkeley/cs/app",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "hotkey",
    size = "small",
    srcs = ["HotKeyGenerator_T.java"],
    test_class = "edu.berkeley.cs.app.HotKeyGenerator_T",
    deps = [
        "//java/src/edu/berkeley/cs/app",
        "//java/src/edu/berkeley/cs/util",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "sort_checker",
    size = "small",
    srcs = ["SortChecker_T.java"],
    test_class = "edu.berkeley.cs.app.SortChecker_T",
    deps = [
        "//java/src/edu/berkeley/cs/app",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "duplicate_usernames",
    size = "small",
    srcs = ["DuplicateUsernames_T.java"],
    test_class = "edu.berkeley.cs.app.DuplicateUsernames_T",
    deps = [
        "//java/src/edu/berkeley/cs/app",
        "//java/src/edu/berkeley/cs/util",
        "//thirdparty:junit4",
    ],
)
