package(default_visibility = ["//visibility:public"])

java_test(
    name = "graph",
    size = "small",
    srcs = ["Graph_T.java"],
    test_class = "edu.berkeley.cs.graph.Graph_T",
    deps = [
        "//java/src/edu/berkeley/cs/graph",
        "//java/test/edu/berkeley/cs/util:utilities",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "digraph",
    size = "small",
    srcs = ["DirectedGraph_T.java"],
    test_class = "edu.berkeley.cs.graph.DirectedGraph_T",
    deps = [
        "//java/src/edu/berkeley/cs/graph",
        "//java/test/edu/berkeley/cs/util:utilities",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "dfs",
    size = "small",
    srcs = ["DepthFirstSearch_T.java"],
    test_class = "edu.berkeley.cs.graph.DepthFirstSearch_T",
    deps = [
        "//java/src/edu/berkeley/cs/graph",
        "//java/test/edu/berkeley/cs/util:utilities",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "bfs",
    size = "small",
    srcs = ["BreadthFirstSearch_T.java"],
    test_class = "edu.berkeley.cs.graph.BreadthFirstSearch_T",
    deps = [
        "//java/src/edu/berkeley/cs/graph",
        "//java/test/edu/berkeley/cs/util:utilities",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "cycle",
    size = "small",
    srcs = ["Cycle_T.java"],
    test_class = "edu.berkeley.cs.graph.Cycle_T",
    deps = [
        "//java/src/edu/berkeley/cs/graph",
        "//java/src/edu/berkeley/cs/util",
        "//java/test/edu/berkeley/cs/util:utilities",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "dfsorder",
    size = "small",
    srcs = ["DepthFirstOrder_T.java"],
    test_class = "edu.berkeley.cs.graph.DepthFirstOrder_T",
    deps = [
        "//java/src/edu/berkeley/cs/graph",
        "//java/test/edu/berkeley/cs/util:utilities",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "toposort",
    size = "small",
    srcs = ["TopologicalSort_T.java"],
    test_class = "edu.berkeley.cs.graph.TopologicalSort_T",
    deps = [
        "//java/src/edu/berkeley/cs/graph",
        "//java/test/edu/berkeley/cs/util:utilities",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "scc",
    size = "small",
    srcs = ["StronglyConnectedComponents_T.java"],
    test_class = "edu.berkeley.cs.graph.StronglyConnectedComponents_T",
    deps = [
        "//java/src/edu/berkeley/cs/graph",
        "//java/test/edu/berkeley/cs/util:utilities",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "mst",
    size = "small",
    srcs = ["MinimumSpanningTree_T.java"],
    test_class = "edu.berkeley.cs.graph.MinimumSpanningTree_T",
    deps = [
        "//java/src/edu/berkeley/cs/graph",
        "//java/src/edu/berkeley/cs/util",
        "//java/test/edu/berkeley/cs/util:utilities",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "sp",
    size = "small",
    srcs = ["ShorestPath_T.java"],
    test_class = "edu.berkeley.cs.graph.ShorestPath_T",
    deps = [
        "//java/src/edu/berkeley/cs/graph",
        "//java/test/edu/berkeley/cs/util:utilities",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "mssp",
    size = "small",
    srcs = ["MultipleSourceShortestPath_T.java"],
    test_class = "edu.berkeley.cs.graph.MultipleSourceShortestPath_T",
    deps = [
        "//java/src/edu/berkeley/cs/graph",
        "//java/test/edu/berkeley/cs/util:utilities",
        "//thirdparty:junit4",
    ],
)
