package(default_visibility = ["//visibility:public"])

py_library(
    name = "utilities",
    srcs = ["utilities.py"],
    deps = ["//python/src/graph"],
)

py_test(
    name = "linkedlist",
    srcs = ["linkedlist.py"],
    deps = ["//python/src/util"],
)

py_test(
    name = "splaylist",
    srcs = ["splaylist.py"],
    deps = ["//python/src/util"],
)

py_test(
    name = "queue",
    srcs = ["queue.py"],
    deps = ["//python/src/util"],
)

py_test(
    name = "stack",
    srcs = ["stack.py"],
    deps = ["//python/src/util"],
)

py_test(
    name = "minheap",
    srcs = ["minheap.py"],
    deps = ["//python/src/util"],
)

py_test(
    name = "treemap",
    srcs = ["treemap.py"],
    deps = ["//python/src/util"],
)

py_test(
    name = "hashmap",
    srcs = ["hashmap.py"],
    deps = ["//python/src/util"],
)

py_test(
    name = "hashset",
    srcs = ["hashset.py"],
    deps = ["//python/src/util"],
)

py_test(
    name = "unionfind",
    srcs = ["union_find.py"],
    main = "union_find.py",
    deps = ["//python/src/util"],
)
