package(default_visibility = ["//visibility:public"])

java_test(
    name = "insertion",
    size = "small",
    srcs = ["Insertion_T.java"],
    test_class = "edu.berkeley.cs.sort.Insertion_T",
    deps = [
        "//java/src/edu/berkeley/cs/sort:insertion",
        "//java/test/edu/berkeley/cs/util:utilities",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "selection",
    size = "small",
    srcs = ["Selection_T.java"],
    test_class = "edu.berkeley.cs.sort.Selection_T",
    deps = [
        "//java/src/edu/berkeley/cs/sort:selection",
        "//java/test/edu/berkeley/cs/util:utilities",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "shell",
    size = "small",
    srcs = ["Shell_T.java"],
    test_class = "edu.berkeley.cs.sort.Shell_T",
    deps = [
        "//java/src/edu/berkeley/cs/sort:shell",
        "//java/test/edu/berkeley/cs/util:utilities",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "merge",
    size = "small",
    srcs = ["Merge_T.java"],
    test_class = "edu.berkeley.cs.sort.Merge_T",
    deps = [
        "//java/src/edu/berkeley/cs/sort:merge",
        "//java/src/edu/berkeley/cs/util:linkedlist",
        "//java/test/edu/berkeley/cs/util:utilities",
        "//thirdparty:junit4",
    ],
)

java_test(
    name = "quick",
    size = "small",
    srcs = ["Quick_T.java"],
    test_class = "edu.berkeley.cs.sort.Quick_T",
    deps = [
        "//java/src/edu/berkeley/cs/sort:quick",
        "//java/test/edu/berkeley/cs/util:utilities",
        "//thirdparty:junit4",
    ],
)
